module.exports = {
  prod_wechat: {
    appID: `wx94f7ded2a2b0a038`, // 开发者 id
    AppSecret: `f97d8691a36c5a67d4e597db7e470a93`,
    token: `vast`,
  },
  test_wechat: {
    appID: `wx96e239a9e4bbbdcc`,
    appsecret: `ebac5b3d971ade3c5333a858ab9eaa36`,
    URL: `http://vast.free.idcfengye.com/wx`,
    Token: `test`,
  },
  scopes: {
    snsapi_base: `snsapi_base`,
    snsapi_userinfo: `snsapi_userinfo`,
  },
  jsApiList: [
    'updateAppMessageShareData',
    'updateTimelineShareData',
    'onMenuShareWeibo',
    'onMenuShareQZone',
    'startRecord',
    'stopRecord',
    'onVoiceRecordEnd',
    'playVoice',
    'pauseVoice',
    'stopVoice',
    'onVoicePlayEnd',
    'uploadVoice',
    'downloadVoice',
    'chooseImage',
    'previewImage',
    'uploadImage',
    'downloadImage',
    'translateVoice',
    'getNetworkType',
    'openLocation',
    'getLocation',
    'hideOptionMenu',
    'showOptionMenu',
    'hideMenuItems',
    'showMenuItems',
    'hideAllNonBaseMenuItem',
    'showAllNonBaseMenuItem',
    'closeWindow',
    'scanQRCode',
    'chooseWXPay',
    'openProductSpecificView',
    'addCard',
    'chooseCard',
    'openCard',
  ],
}
